Add missing cmake dep for StablehloBroadcastLowering (#2973)
Ninja 'missingdeps' tool reports:

    $ cmake --build build -- -t missingdeps

    Missing dep: <...>StablehloBroadcastLowering.cpp.o uses
    <...>/build/stablehlo/dialect/BaseAttrInterfaces.h.inc (generated by
    CUSTOM_COMMAND)

    Missing dep: <...>StablehloBroadcastLowering.cpp.o uses
build/stablehlo/dialect/StablehloAttrs.h.inc (generated by
CUSTOM_COMMAND)

    Missing dep: <...>StablehloBroadcastLowering.cpp.o uses
build/stablehlo/dialect/StablehloEnums.h.inc (generated by
CUSTOM_COMMAND)

    Missing dep: <...>StablehloBroadcastLowering.cpp.o uses
build/stablehlo/dialect/StablehloOps.h.inc (generated by CUSTOM_COMMAND)

    Missing dep: <...>StablehloBroadcastLowering.cpp.o uses
    build/stablehlo/dialect/StablehloTypeDefs.h.inc (generated by
    CUSTOM_COMMAND)

    Processed 412 nodes.
    Error: There are 1 missing dependency paths.

1 targets had depfile dependencies on 5 distinct generated inputs (from
1
    rules) without a non-depfile dep path to the generator.

There might be build flakiness if any of the targets listed above are
built
    alone, or not late enough, in a clean output directory.

Add generated tablegen targets to it (bazel already has .inc files in
:base), so we get:

    $ cmake --build build -- -t missingdeps
    Processed 412 nodes.
    No missing dependencies on generated files found.

Co-authored-by: Matthias Guenther <mrguenther@google.com>